services:

  judge0-server:
    image: judge0/judge0:1.13.1
    ports:
      - "2358:2358"
    env_file:
      - ./judge0.conf
    environment:
      POSTGRES_HOST: judge0-db
      REDIS_HOST: judge0-redis
    privileged: true
    restart: unless-stopped
    depends_on:
      judge0-db:
        condition: service_healthy
      judge0-redis:
        condition: service_started

  judge0-workers:
    image: judge0/judge0:1.13.1
    env_file:
      - ./judge0.conf
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    environment:
      POSTGRES_HOST: judge0-db
      REDIS_HOST: judge0-redis
    privileged: true
    restart: unless-stopped
    depends_on:
      judge0-db:
        condition: service_healthy
      judge0-redis:
        condition: service_started

  judge0-db:
    image: postgres:16
    env_file:
      - ./judge0.conf
    environment:
      POSTGRES_PASSWORD: judge0pass
    volumes:
      - judge0-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U judge0"]
      interval: 5s
      timeout: 5s
      retries: 10

  judge0-redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "somepassword"]
    volumes:
      - judge0-redis-data:/data

volumes:
  judge0-db-data:
  judge0-redis-data:
